CREATE TABLE caixa (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    operacao VARCHAR(30) NOT NULL,
	data_operacao DATE,
	valor DECIMAL(10,2) NOT NULL,
	referente VARCHAR(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;